import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  /**
   * @section 算想三千页面配置
   *
   * @description
   * 会自动生成对应于 `docs/sx3k` 目录下的文件结构。
   * 自动生成意味着该侧边栏项会映射文件夹中的 Markdown 文件和子文件夹，形成文档的层次结构。
   */
  sx3k: [
    {
      type: "autogenerated",
      dirName: "sx3k",
    },
  ],

  /**
   * @section 文档页面配置
   *
   * @description
   * 对应于项目中 `docs/document` 文件夹。
   * 同样采用自动生成功能，根据目录结构动态构建侧边栏菜单项，便于管理和导航文档内容。
   */
  document: [
    {
      type: "autogenerated",
      dirName: "document",
    },
  ],
};

export default sidebars;
