import Head from "next/head";
import Cover from "@/components/home/Cover";
import Description from "@/components/home/Description";
import QrCodePanel from "@/components/home/QrCodePanel";
import { Box } from "@mui/material";
import AppContainer from "@/components/home/AppContainer";

export default function Home() {
  return (
    <>
      <Head>
        <title>算网是为中国 AI 经济而生的 AI IaaS Cloud</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppContainer>
          <Box className="home_page_wrap">
            <Cover />
            <Description />
            <QrCodePanel />
          </Box>
        </AppContainer>
      </main>
    </>
  );
}
