import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import Cover from "@/components/home/Cover";
import Description from "@/components/home/Description";
import QrCodePanel from "@/components/home/QrCodePanel";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>nascentcore.ai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            background: "linear-gradient(to bottom,transparent,rgb(255,255,255))rgb(0,0,0)",
          }}
        >
          <Cover />
          <Description />
          <QrCodePanel />
        </Box>
      </main>
    </>
  );
}
